/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repositoriotests;

public class App {

    public void testRegistrarUsuario() {
        GestorUsuarios gestorUsuarios = new GestorUsuarios();
        String nombreUsuario = "usuario1";
        String correoElectronico = "usuario1@example.com";

        assertTrue(gestorUsuarios.registrarUsuario(nombreUsuario, correoElectronico));
    }

    private void assertTrue(Object registrarUsuario) {
        throw new UnsupportedOperationException("Unimplemented method 'assertTrue'");
    }

    public void testEliminarUsuario() {
        GestorUsuarios gestorUsuarios = new GestorUsuarios();
        String nombreUsuario = "usuario2";
        String correoElectronico = "usuario2@example.com";

        gestorUsuarios.registrarUsuario(nombreUsuario, correoElectronico);
        assertTrue(gestorUsuarios.eliminarUsuario(nombreUsuario));
    }
}

/*
Proposta 1

Gestió d'Usuaris:
registrar_usuari(nom_usuari, correu_electronic): Registra un nou usuari.
eliminar_usuari(nom_usuari): Elimina un usuari existent.

 */