/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repositoriotests;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void appSumaCorrecta() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.sumar(1,3));
    }
    @Test void appRestaCorrecta(){
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.restar(1,2));
    }
}