/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repositoriotests;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    public static void main(String[] args) {
        GestorUsuarios gestorUsuarios = new GestorUsuarios();

        String nombreUsuario = "usuario1";
        String correoElectronico = "usuario1@example.com";
        gestorUsuarios.registrarUsuario(nombreUsuario, correoElectronico);
        System.out.println("Usuario registrado: " + nombreUsuario);

        String nombreUsuarioEliminar = "usuario1";
        if (gestorUsuarios.eliminarUsuario(nombreUsuarioEliminar)) {
            System.out.println("Usuario eliminado: " + nombreUsuarioEliminar);
        } else {
            System.out.println("El usuario no existe: " + nombreUsuarioEliminar);
        }
    }
}